### ISSUE TITLE
ci: fixing up the ci pipeline

### ISSUE THREAD

**Issue by arunavabasucom** [arunavabasu-03/stabo#3]
### **Tasks -** 

- [ ] android ci build .apk 
- [ ] android prod build for googleplay 
- [ ] ios ci build .ipa file 
- [ ] ios prod build
